
language: r

r:
  - oldrel
  - release
  - devel

cache: packages

sudo: false

# To CRAN, warnings <are> errors.
warnings_are_errors: true

os:
- linux
- osx

#r_github_packages:
#  - r-lib/covr

addons:
  apt:
    packages:
      - libgdal-dev
      - libproj-dev
      
before_install:
 - Rscript -e 'update.packages(ask = FALSE)'
  
after_success:
#- Rscript -e 'covr::codecov()'
- if [[ "$TRAVIS_OS_NAME" = 'linux' ]]; then R CMD INSTALL *tar.gz; fi

notifications:
  email:
    on_success: change
    on_failure: change
